### ISSUE TITLE
Invalid shape error RainSynAll100 test

### ISSUE THREAD

**Issue by tuomasv-flwls** [TonyHongtaoWu/RainMamba#2]
Getting the following error when trying to run `RainSynAll100`
`CUDA_VISIBLE_DEVICES=0 bash ./tools/dist_test.sh configs/derainers/RainMamba/RainSynAll100.py "RainSynAll100.pth" 1 --save-path '../results/RainSynAll100/'`
```
File "/RainMamba/code/RainSynAll100/modules/mambablock.py", line 19, in forward
    x = x.transpose(1, 2).contiguous().reshape(B, C, nf, H, W)
RuntimeError: shape '[1, 256, 3, 64, 64]' is invalid for input of size 1310720
```

Was able to train the model without any problems.

By the way, is it possible to make the pre-trained models publicly available? Currently they require approval.

Thanks!

**Comment by TonyHongtaoWu** [comment]
1. The reason for the error is that the size of the input image and the order of the curve are inconsistent.
You can use the newly revised code below
RainMamba/code/RainSynAll100/mmedit/models/derainers/DrainNet. py.
2. Thank you for your reminder! I used to think they were already accessible because they could be accessed normally on my device. I will fix this issue immediately.
